# Generated by Django 2.1.1 on 2018-10-07 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0002_auto_20180917_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('dimension_x', models.IntegerField(default=0)),
                ('dimension_y', models.IntegerField(default=0)),
                ('grid', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='curr_x',
            new_name='current_x',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='curr_y',
            new_name='current_y',
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robo.Warehouse'),
        ),
        migrations.AddField(
            model_name='robot',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robo.Warehouse'),
        ),
    ]
