# Generated by Django 2.1.1 on 2018-10-10 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0003_auto_20181007_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='position_x',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='position_y',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='robot',
            name='battery',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='robot',
            name='current_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='robot',
            name='current_y',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='orientation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='robot',
            name='target_orientation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='robot',
            name='target_x',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='target_y',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='dimension_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='dimension_y',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
