# Generated by Django 2.1.1 on 2018-10-29 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0004_auto_20181010_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='robot',
            name='battery',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='current_y',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='robot',
            name='orientation',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='target_orientation',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='target_x',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='target_y',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='dimension_x',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='dimension_y',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
