# Generated by Django 2.1.1 on 2018-10-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0005_auto_20181029_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='name',
            new_name='person',
        ),
    ]
